### ISSUE TITLE
Performance Comparison

### ISSUE THREAD

**Issue by kbrock** [matsumoto-r/ngx_mruby#102]
Hello,

This looks great.

http://www.techempower.com/benchmarks/ is a popular framework for comparing functionality across web technologies. There is a benchmark for [openresty][] which would probably be similar to `ngx_mruby`.

Have you though about implementing these benchmarks?
Does `ngx_mruby` have the necessary libraries to implement those benchmarks?

Thank you.

[openresty]: http://github.com/TechEmpower/FrameworkBenchmarks/tree/master/frameworks/Lua/openresty

**Comment by matsumoto-r** [comment]
Hi, @kbrock 

ngx_mruby seems to be failed at the TechEmpower/TFB-Round-10 benchmark. 

https://github.com/TechEmpower/TFB-Round-10/blob/master/peak/linux/results-2015-03-06-peak-preview3/latest/logs/ngx_mruby/err.txt

Do you know what is happening?

**Comment by matsumoto-r** [comment]
[The ec2/linux benchmark](https://github.com/TechEmpower/TFB-Round-10/blob/master/ec2/linux/results-2015-01-27-ec2-preview1/latest/logs/ngx_mruby/out.txt) was success. hmm,,,

**Comment by kbrock** [comment]
Unfortunately the benchmarks are sporadic.

I am not using a connection pool, which is probably not good. Though I don't think this is the problem

**Comment by matsumoto-r** [comment]
@kbrock hmm... [peak/linux of ngx_mruby](https://github.com/TechEmpower/TFB-Round-10/tree/master/peak/linux) were all failed. Is this also sporadic?

**Comment by kbrock** [comment]
I mistyped before. I should have said "tests in travis have sporadic failures"
I think the benchmarks the way they are running them should always work.

I wonder if this has to do with the lack of connection pool catching up with us.

**Comment by triptec** [comment]
@kbrock I looked att the repo and found that i looks like you've worked on the fortune test as well, any particular reason it's not there?

**Comment by kbrock** [comment]
Hello @triptec,

Need to incorporate a templating library like [erb](https://github.com/pbosetti/mruby-merb). It is required by the specifications.

**Comment by matsumoto-r** [comment]
Oh, already fixed this. https://github.com/TechEmpower/TFB-Round-10/blob/master/peak/linux/results-2015-03-11-peak-preview5/latest/logs/ngx_mruby/out.txt

**Comment by matsumoto-r** [comment]
@kbrock I got the result and it's quite nice! thanks a lot!
