### ISSUE TITLE
Mapping multiple urls to same ruby files

### ISSUE THREAD

**Issue by kbrock** [matsumoto-r/ngx_mruby#104]
Hello.

I created a ruby file (`World`) that I want to use across multiple urls:

```
class World
  def db
    @db ||= Userdata.new("my_#{Process.pid}").db
  end

  def find(id)
    ret = nil
    db.execute("select * from World where id = ?", id) do |row, fields|
      ret = Hash[fields.zip(row)]
    end
    ret
  end

  def save(world)
    db.execute("update World set randomNumber = ? where id = ?", world["randomNumber"], world["randomNumber"])
  end
end

r = Nginx::Request.new

num_queries = r.var.arg_queries.to_i
num_queries = 1 if num_queries < 0
num_queries = 500 if num_queries > 500

world = World.new
ret = num_queries.times.map { world.find(rand(10000)) }
Nginx.rputs JSON::stringify(ret)
```

Would you suggest mapping all the urls to a single file using something like https://github.com/mattn/mruby-sinatic ?

Have you played with frameworks and ngx_mruby?
Does it decrease the performance by too much?

Sure feels like a single url would map ngx_mruby to be like typical ruby and rails/sinatra.

Just looking for your thoughts.
Thanks

**Comment by kbrock** [comment]
answer: This would be solved with a require. Since mruby has no require, use something like sinatic instead.

**Comment by matsumoto-r** [comment]
If you map multiple urls to same ruby files, hooking only the ruby file which defined `World` class at ``mruby_init_worker`` phase.
