### ISSUE TITLE
Cannot return anything

### ISSUE THREAD

**Issue by ephracis** [matsumoto-r/ngx_mruby#113]
You should change "return" to "Nginx.return" in https://github.com/matsumoto-r/ngx_mruby/wiki/Class-and-Method#nginxreturn

**Comment by matsumoto-r** [comment]
Hi, ngx_mruby can't return Nginx::HTTP_FORBIDDEN from main. So, you should use `Nginx.return Nginx::HTTP_FORBIDDEN` at the end.

```
if access == true 
  # pass to the next hook phase
  Nginx.return Nginx::DECLINED
else
  Nginx.return Nginx::HTTP_FORBIDDEN
end
```

**Comment by matsumoto-r** [comment]
Can I close this? @ephracis
