### ISSUE TITLE
Trouble compiling nginx

### ISSUE THREAD

**Issue by simo2409** [matsumoto-r/ngx_mruby#115]
I'm trying to build ngx_ruby in an exact copy of a production environment (centos7 + nginx + passenger + some external modules) but I'm getting troubles compiling it.

(all previous steps of installation went without problems)

I'm adding ngx_mruby via `--add-module=` and my complete command is:
``
sudo /usr/local/bin/passenger-install-nginx-module --auto --prefix=/opt/nginx --languages=ruby --nginx-source-dir=/tmp/nginx-1.6.1 --extra-configure-flags="--add-module=/tmp/headers-more-nginx-module --add-module=/tmp/ngx_pagespeed-1.9.32.1-beta --with-http_stub_status_module --without-http_autoindex_module --without-http_ssi_module --without-http_browser_module --without-http_empty_gif_module --without-http_fastcgi_module --without-http_limit_req_module --without-http_limit_conn_module --without-http_memcached_module --without-http_proxy_module --without-http_referer_module --without-http_scgi_module --without-http_split_clients_module --without-http_upstream_ip_hash_module --without-http_userid_module --without-http_uwsgi_module --with-http_gzip_static_module --with-http_ssl_module --with-http_spdy_module --add-module=/home/vagrant/ngx_mruby --add-module=/home/vagrant/ngx_mruby/dependence/ngx_devel_kit"
``

The error I'm getting is: http://pastie.org/10122799 (I'm sorry but I'm not able to understand the error)

Thank you very much

**Comment by matsumoto-r** [comment]
Hi, Did you run `make build_mruby`? 

For example,

```
$ cd ${NGX_MRUBY_SRC}
$ ./configure --with-ngx-src-root=${NGINX_SRC}
$ make build_mruby
$ make generate_gems_config
$ cd ${NGINX_SRC}
$ ./configure --prefix=/usr/local/nginx --add-module=${NGX_MRUBY_SRC} --add-module=${NGX_MRUBY_SRC}/dependence/ngx_devel_kit --add-module=${SOME_OTHER_MODULE}
$ make
```

**Comment by kbrock** [comment]
Think I may have asked before but

1) What does `configure --with-ngx-src-root=${NGINX_SRC}` do?
2) Is there a way to use `ruby-build mruby` or rvm's install?

**Comment by simo2409** [comment]
@matsumoto-r finally I worked around, removing mruby-memcached and refactoring my app's code to use redis I got it working. Sadly I have no more time to try to solve the problem I had with mruby-memcached but to me this issue can be closed

**Comment by matsumoto-r** [comment]
@simo2409 Oh... Sorry I can't help you. I search in GitHub, and found Dockerfile of nginx with ngx_mruby and memcached. https://github.com/tacahilo/docker-ngx_mruby-memcached/blob/master/centos6/Dockerfile#L12-L16

They used libmemcached-last-devel in remi repository, and ngx_mruby works well. 

OK, so I closed this for now. But if you have any questions, feel free to reopen this issue! Thanks for your report.
