### ISSUE TITLE
Content type issues with json

### ISSUE THREAD

**Issue by zzak** [matsumoto-r/ngx_mruby#125]
Hello matz-r!

I've created a [minimal example](https://github.com/zzak/ngx-bugs) of the content type bugs I was describing to you.

When you run the command in step 3 (see README), the content-type will eventually break.

I have narrowed it down to the JSON gem, when parsing any sized data set you will see the bug:
https://github.com/zzak/ngx-bugs/blob/master/docker/hook/test.rb#L7

However, it seems to be easier to reproduce with bigger data sets.
I mean: `more data == more frequent`

**Comment by zzak** [comment]
also /cc @mattn

**Comment by matsumoto-r** [comment]
Thank you for your report. I'll investigate it.

**Comment by kbrock** [comment]
so is this a multi-threading issue?

**Comment by matsumoto-r** [comment]
> so is this a multi-threading issue?

A nginx worker is not multi-thread, and ngx_mruby has mrb_state per process. So, it seems not to be multi-threading issue.

**Comment by matsumoto-r** [comment]
@zzak I fixed this issue via #126 . Please check it.
