### ISSUE TITLE
undefined method `popen2e' for Open3:Module 

### ISSUE THREAD

**Issue by paavalan** [matsumoto-r/ngx_mruby#127]
getting error while build

build: [exec] git clone git://github.com/redis/hiredis.git
rake aborted!
undefined method `popen2e' for Open3:Module

(See full trace by running task with --trace)
make: *** [build_mruby] Error 1

**Comment by matsumoto-r** [comment]
You should use the Ruby1.9 or more versions.

**Comment by paavalan** [comment]
@matsumoto-r thanks
