### ISSUE TITLE
difference between mruby_output_filter and mruby_output_filter_code

### ISSUE THREAD

**Issue by takeswim** [matsumoto-r/ngx_mruby#142]
mruby_output_filterとmruby_output_filter_codeで動作が違っている様に見えます。

https://github.com/takeswim/ngx_mruby_filtersample

```
[root@instance-1 conf]# curl -l http://localhost:19999
curl: (52) Empty reply from server
[root@instance-1 conf]# curl -l http://localhost:19998
PORT 7779 CONTENTS
 WORLD
```

nginx: 1.9.3
ngx_mruby: b6db5e73acd1d7
で実験しています。

**Comment by matsumoto-r** [comment]
ありがとうございます、これはおかしいですね。修正します。

**Comment by matsumoto-r** [comment]
@takeswim 
#143 で直しておきました。ご確認下さい。問題なければcloseお願いします。

**Comment by takeswim** [comment]
ありがとうございます。問題なくフィルタ処理できることを確認しました。
