### ISSUE TITLE
Send file 

### ISSUE THREAD

**Issue by davydovanton** [matsumoto-r/ngx_mruby#144]
Hello!
I have strange question but how I can send file from ngx_mruby?

@matsumoto-r

**Comment by matsumoto-r** [comment]
Hi, you can use Nginx::Request#uri= or Nginx.redirect .

**Comment by davydovanton** [comment]
I need to send my local image, from example. I understand right that I need to write smth like this:
```
r = Nginx::Request.new
r.uri = 'path/to/local/file.jpg'
```
?

**Comment by matsumoto-r** [comment]
Yes, you should write a relative path from the document root.

**Comment by davydovanton** [comment]
thanks!
