### ISSUE TITLE
ngx_mruby examples

### ISSUE THREAD

**Issue by matsumoto-r** [matsumoto-r/ngx_mruby#158]
https://github.com/hsbt/nginx-tech-talk

@hsbt 's ngx_mruby examples are very useful. So, I'd like to point this link from ngx.mruby.org or a directory of ngx_mruby repository.

What do you think? cc/ @kbrock @hsbt 

ref: https://github.com/matsumoto-r/ngx_mruby/pull/145#issuecomment-169654290

**Comment by hsbt** [comment]
> I'd like to point this link from ngx.mruby.org

It's ok for temporary references. I will update showcase of ngx_mruby usage at it's repository.

**Comment by matsumoto-r** [comment]
@hsbt Thank you for your cooperation. I'll add that link.

**Comment by matsumoto-r** [comment]
done via 9c1ba8b

**Comment by kbrock** [comment]
@matsumoto-r thank you for adding these.

Examples help so much
