### ISSUE TITLE
Convert the module to be dynamically loadable under 1.9.11

### ISSUE THREAD

**Issue by sampointer** [matsumoto-r/ngx_mruby#164]
https://www.nginx.com/resources/wiki/extending/converting/ defines the steps required to convert modules to be dynamically loadable.

It would be a great help and an aid to adoption in installations where bespoke compilations of nginx cannot be employed.

**Comment by matsumoto-r** [comment]
Thank you for your information. I also want to support both statically and dynamically loadable module.

**Comment by matsumoto-r** [comment]
v1.7.12 supported. ref: https://github.com/matsumoto-r/ngx_mruby/releases/tag/v1.17.2
