### ISSUE TITLE
Proposal for Rack based API change for error pages

### ISSUE THREAD

**Issue by yyamano** [matsumoto-r/ngx_mruby#179]
I'd like to use Rack based API for an error page as below.

```
location /api {
  error_page 401 @error;
  mruby_access_handler /opt/nginx/lib/mruby/auth.rb;
  proxy_pass http://localhost:4567/hello;
}
location @error {
  mruby_content_handler /opt/nginx/lib/mruby/error.rb;
}
```

```
class ErrorResponse
  def call(env)
    return [401, [], ["Unauthorized"]]
  end
end
run ErrorResponse.new
```

It doesn't work as I expected. I get nginx's default error page.

The current implementation calls Nginx.return with a status returned by "call" method.
https://github.com/matsumoto-r/ngx_mruby/blob/master/mrbgems/rack-based-api/mrblib/rack.rb#L90
In my observation, the call causes special response handling for 401 again.

So I’d like to propose to change rack.rb as follows. With this change, 'return [nil, [], ["Unauthorized"]]' works well to me.

```
diff --git a/mrbgems/rack-based-api/mrblib/rack.rb b/mrbgems/rack-based-api/mrblib/rack.rb
index 3ec7c01..57498b4 100644
--- a/mrbgems/rack-based-api/mrblib/rack.rb
+++ b/mrbgems/rack-based-api/mrblib/rack.rb
@@ -75,6 +75,8 @@ module Kernel
     end
 
     def self.build_response r, res
+      return if res.nil?
+
       if res[1].kind_of?(Hash)
         res[1].keys.each { |k| r.headers_out[k] = res[1][k] }
       elsif res[1].kind_of?(Array)
@@ -87,7 +89,7 @@ module Kernel
       else
         raise TypeError, "response body arg type must be Array"
       end
-      Server.return res[0].to_i
+      Server.return res[0].to_i if res[0]
     end
   end

```

**Comment by matsumoto-r** [comment]
Thank you for your proposal. It looks good to me. Could you send the PR?

**Comment by yyamano** [comment]
Will do next week.

**Comment by yyamano** [comment]
Just sent a pull request.
https://github.com/matsumoto-r/ngx_mruby/pull/180

**Comment by matsumoto-r** [comment]
Oh, CI was failed.
