### ISSUE TITLE
test.sh with BUILD_DYNAMIC_MODULE and --with-openssl-src fails

### ISSUE THREAD

**Issue by yyamano** [matsumoto-r/ngx_mruby#203]
test.sh doesn't work as I expected.

```
% env BUILD_DYNAMIC_MODULE=t sh ./test.sh --with-openssl-src=/home/vagrant/openssl-1.0.2h
[snip]
/usr/bin/ld: /home/vagrant/openssl-1.0.2h/.openssl/lib/libssl.a(ssl_lib.o): 再配置 R_X86_64_32 (`.rodata.str1.1' に対する) は>共有オブジェクト作成時には使用できません。-fPIC を付けて再コンパイルしてください。
/home/vagrant/openssl-1.0.2h/.openssl/lib/libssl.a: シンボルを読み込めませんでした: 不正な値です
collect2: エラー: ld はステータス 1 で終了しました
```

There are two problems in Makefile.in. The first one is linking static libraries at https://github.com/matsumoto-r/ngx_mruby/blob/master/Makefile.in#L50-L56

```
ifdef NGX_OPENSSL_SRC
  NGX_OPENSSL_LIBS = $(NGX_OPENSSL_SRC)/.openssl/lib/libssl.a $(NGX_OPENSSL_SRC)/.openssl/lib/libcrypto.a
  CFLAGS := -I$(NGX_OPENSSL_SRC)/.openssl/include $(CFLAGS)
  LDFLAGS := -L$(NGX_OPENSSL_SRC)/.openssl/lib $(LDFLAGS)
  LIBS := $(NGX_OPENSSL_LIBS) $(LIBS)
  build_mruby_targets := openssl
endif
```

The second problem is openssl compile options at https://github.com/matsumoto-r/ngx_mruby/blob/master/Makefile.in#L104-L109

```
openssl:
        cd $(NGX_OPENSSL_SRC) \
        && if [ -f Makefile ]; then $(MAKE) clean; fi \
        && ./config --prefix=$(NGX_OPENSSL_SRC)/.openssl no-shared $(NGX_OPENSSL_OPT)  \
        && $(MAKE) \
        && $(MAKE) install_sw LIBDIR=lib
```

.travis.yml uses different options as below:

```
  - ./config --prefix=/usr/local --shared zlib -fPIC enable-tlsext >> /dev/null 2>&1
```

So my questions are:

* Do you want to fix it, or not?
* Can we use same options in both .travis.yml and Makefie.in?

I don't have much opinion on it. Because I don't use openssl at my project. I use it only for pull requests.

**Comment by matsumoto-r** [comment]
Thank you for your report.

> Do you want to fix it, or not?

I want to fix it. 

> Can we use same options in both .travis.yml and Makefie.in?

Yes!!
