### ISSUE TITLE
`mruby_post_read_handler` not running in 1.18.3+

### ISSUE THREAD

**Issue by hone** [matsumoto-r/ngx_mruby#210]
I tried upgrading my ngx_mruby and it caused my `mruby_post_read_handler` to stop working in the [heroku-buildpack-static](https://github.com/heroku/heroku-buildpack-static/blob/master/scripts/config/templates/nginx.conf.erb#L46). Did something change? Downgrading back to `1.18.2` fixed it for me.

**Comment by yyamano** [comment]
I guess my change 9668ce62d759796c9abf6f73c4a8c23abc71d725 causes the problem.
The original code copied configurations from child to parent in ngx_http_mruby_merge_loc_conf(). 
It is incorrect, but it made possible to define mruby_post_read_handler inside location.

https://github.com/matsumoto-r/ngx_mruby/blob/v1.18.4/src/http/ngx_http_mruby_module.c#L1919-L1920

```
    ngx_http_mruby_main_conf_t *mmcf = ngx_http_get_module_main_conf(r, ngx_http_mruby_module);                        \
    ngx_http_mruby_loc_conf_t *mlcf = ngx_http_get_module_loc_conf(r, ngx_http_mruby_module);
```

ngx_http_mruby_post_read_handler() tries to get a location configuration that matches url path, but it fails. The handler runs in NGX_HTTP_POST_READ_PHASE. I think it doesn’t work before NGX_HTTP_FIND_CONFIG_PHASE.

@matsumoto-r Any thoughts on my analysis?

I’ll be AFK for a week .

**Comment by matsumoto-r** [comment]
@hone Thank you for your issue, and sorry for my late response. I start to investigate this bug.

**Comment by matsumoto-r** [comment]
@yyamano Your analysis is right. So, ngx_mruby don't allow post_read directives on location context via #217 .

@hone Please replace the post_read directive into main context since the post_read directive of v1.18.2 also actually worked in the manner on main context.

**Comment by matsumoto-r** [comment]
Rleased v1.18.5, thanks!
