### ISSUE TITLE
Proposal: mutex across worker processes

### ISSUE THREAD

**Issue by yangyuqian** [matsumoto-r/ngx_mruby#212]
Hi, @matsumoto-r 

Recently I need a mutex allowing multiple worker processes to modify shared memory(cached by https://github.com/matsumoto-r/mruby-localmemcache) synchronously.

i.e.

```
m = GlobalMutex.new
m.lock
# do somthing here
m.unlock
```

Currently, the Mutex(https://github.com/matsumoto-r/mruby-mutex) has only single process support.

Is it possible to add this global mutex support though?

**Comment by matsumoto-r** [comment]
mruby-mutex already supported global mutex. 

refs: https://github.com/matsumoto-r/mruby-mutex/blob/master/src/mrb_mutex.c#L45-L94 https://github.com/matsumoto-r/http-dos-detector/blob/master/dos_detector/dos_detector_init.rb#L1

**Comment by yangyuqian** [comment]
Thanks for doing this, it's really helpful to Rubyers!
